### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by ljcond** [arx-deidentifier/arx#196] opened 2018-05-23 19:35 UTC
I am new to ARX and just trying to test and see if we could use this tool for data masking.

I downloaded the latest version of ARX. I am able to connect to Oracle database(says 'Successfully connected to database') and then, it is not able to move on to next screen. It keeps spinning in there.

Could you please help me find the issue? I don't know where the log file is and what to look for, to debug any possible issue?

**Comment by prasser** [comment] 2018-05-24 12:09
Hi,

thanks for your interest in ARX!

Unfortunately, we do not have an Oracle database around, so it is difficult for us to replicate your issue at the moment. Oracle support for ARX was provided by a third-party contributor. I tried to reproduce your problem with a medium-size MySQL database and couldn't find any problems.

As a starting point, the following questions could help to narrow the problem down:
(1) Which version of ARX are you running?
(2) Is the database running on a different host?
(3) How large is the database?
(4) Is ARX producing any CPU load while it hangs (it is reported with name "java" in the process monitor)?
(5) Do you have any Java programming experience or developers that could help us fix this issue together?

Best,
Fabian

**Comment by prasser** [comment] 2018-05-24 16:33
I see. Maybe this is related to issue #184? If I recall correctly, problems with loading data from Oracle databases have been reported a few times now and waiting for a few minutes may also help. In addition it should be possible for you to connect using the ARX API (see Example21 in the source repository).

Unfortunately, I cannot really help to debug this, as I don't have an Oracle database around. If you can get help: the code for importing data into ARX via JDBC is in: src/main/org.deidentifier.arx.io/*JDBC and the code of the SWT import wizard is in: src/gui/org.deidentifier.arx.gui.view.impl.wizard/ImportWizard*

With Java development experience and access to the source code it shouldn't be a big problem to find the cause of your issue and to potentially fix it. I'm happy to assist you with this at any time, if you have further questions. If you find or fix the bug, it would be great if you could contribute your code or findings.

P.S.: A workaround would be to export the table that you want to import into ARX into a CSV-file and then load the file.

**Comment by prasser** [comment] 2019-04-28 17:42
The scalability for large datasets will be improved significantly in the next release. Hope this helps. Closing.

**Closed by prasser** 2019-04-28 17:42 UTC
