### ISSUE TITLE
[BUG] GUI fixed window sizes too small

### ISSUE THREAD

**Issue by jenno-verdonck** [arx-deidentifier/arx#404] opened 2022-08-29 14:25 UTC
**Describe the bug**
Currently the GUI has fixed sizes for hierarchy importing and the settings window. This causes elements of the GUI to be inaccessible. It is possible that there are more windows with the same problem.

**Expected behavior**
Resizable GUI elements or better default including all the elements.

**Screenshots**
Hierarchy import screen
![image](https://user-images.githubusercontent.com/42772246/187223815-ecebfd98-a14e-4c8c-ba2e-9959bde9487a.png)

Project settings menu
![image](https://user-images.githubusercontent.com/42772246/187223978-409d0d2d-3da6-4e35-b00a-46994bcc224f.png)

**ARX GUI (please complete the following information):**
 - OS: Windows
 - Version: 3.9.0

**Comment by jenno-verdonck** [comment] 2022-08-29 14:33
A colleague of mine doesn't seem to have these problems. Could be specific to having a 4K screen attached or windows scaling of elements.

**Comment by prasser** [comment] 2022-08-29 17:45
Thanks a lot for reporting this. This indeed seems to be related to scaling. Unfortunately, these types of issues are not easy to debug. Are you able to run ARX from source and could try fixes?

**Comment by prasser** [comment] 2022-08-29 18:47
I can reproduce this with a scaling factor of 150% on Windows (but not with 125% or 175%).

Some issues have been fixed already in this branch:

https://github.com/arx-deidentifier/arx/tree/dpi-scaling-fixes

Can you give it a try?

**Comment by jenno-verdonck** [comment] 2022-08-30 07:11
Thank you for the quick fix. I have build the new code from source. It seems like the hierarchy import window is fixed. The settings window however still has the same problem. 

Quick question. Would it also be possible to add a scrolbar to the hierarchy import in order to fully preview the hierarchy? Or is this by design just to view the separator usage?

**Comment by prasser** [comment] 2022-08-30 22:42
Thanks for the quick feedback! Fixing the properties dialog is more challenging. We're working on it.

Re: your question: it's implemented that way by design. Idea is to support checking whether separator settings are (likely) correct. Hierarchies can become quite large and would require a virtual table. If you want to take a look at the hierarchy, please import it.

**Comment by prasser** [comment] 2022-09-11 20:38
Preferences should now also be fixed. Can you try this branch again?

https://github.com/arx-deidentifier/arx/tree/dpi-scaling-fixes

**Comment by prasser** [comment] 2022-09-14 21:05
Should work now. Closing.

**Closed by prasser** 2022-09-14 21:05 UTC
Labels: bug

**Comment by jenno-verdonck** [comment] 2022-09-15 08:37
I just build the branch and it still seems to have the same problem.
![image](https://user-images.githubusercontent.com/42772246/190356778-07f03c70-23d6-42cc-8cdd-a5b87aa08c3f.png)

**Comment by prasser** [comment] 2022-09-15 08:48
But now you can scroll (see the scrollbar on the right)...
