### ISSUE TITLE
SW issue

### ISSUE THREAD

**Issue by seorakwon** [arx-deidentifier/arx#308] opened 2020-03-30 15:35 UTC
Good morning,

I´m an engineering student who is doing a  project on anonymisation tools and was testing yours.

There is not much info available, and have seen your tutorial and followed it but my results are different.

- a % of the data is suppressed.
- Could I get access to the datasets in your github

![India analyse utility](https://user-images.githubusercontent.com/54710127/77931615-acf68580-72ac-11ea-8103-14bbb1bd3e4e.jpg)
Attached, I´m sending the print screens
![India configure transformation](https://user-images.githubusercontent.com/54710127/77931628-b1bb3980-72ac-11ea-8202-202e350c4681.jpg)ns

I have also tried sensitive data, and also could not see the tool doing anything to the dataset.

Could you please help me?

I´m doing it the same way and sometimes it works and sometimes it doesnt.

Many thanks

**Comment by prasser** [comment] 2020-06-21 12:39
Thanks for your interest in ARX. However, I'm not able to follow your description. What exactly is the question? Also, several datasets (and example projects) are available in the ARX GitHub repo.

**Comment by prasser** [comment] 2020-07-01 09:48
Closing this issue, as this is not a bug but a question and no additional information has been provided. Please direct future questions to arx.deidentifier@gmail.com

**Closed by prasser** 2020-07-01 09:48 UTC
Labels: question
