### ISSUE TITLE
Fail to start on mac OS High Sierra

### ISSUE THREAD

**Issue by Tyson1986** [arx-deidentifier/arx#242] opened 2018-12-19 20:12 UTC
After clean installation on Mac OS High Sierra I try to open the app and getting:
"You can’t open the application “ARX-3.7.1.app” because it may be damaged or incomplete."

Executable jar works fine:
java -jar -XstartOnFirstThread arx-3.7.1-osx-64.jar

**Comment by nartz** [comment] 2018-12-19 20:31
I was able to replicate this as well on OSX - @prasser maybe during the upload the installer got corrupted?

**Comment by prasser** [comment] 2018-12-19 22:00
Thanks for reporting and replicating this issue! Have you tried any of the potential fixes proposed on the Internet? There might of course also be an issue with the installer/file. We will take a look at this, but this will take some time (very busy at the moment) - Fabian

**Comment by prasser** [comment] 2019-01-03 15:20
Thanks for taking a closer look at this! Interestingly, I am not able to replicate this issue on High Sierra (10.13.6). Are you sure that the issue is not related to your specific installation?

**Comment by gamblenull1996** [comment] 2020-03-03 10:53
When i tried to run  arx-3.8.0-osx-64.jar on my Catalina 10.15.3，the output is
> java -jar arx-3.8.0-osx-64.jar
***WARNING: Display must be created on main thread due to Cocoa restrictions.
and the interface can't be open。

then i tried `java -XstartOnFirstThread -jar arx-3.8.0-osx-64.jar`  works for me.
but still get some warnning

> 2020-03-03 15:25:43.825 java[67280:894725] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
2020-03-03 15:33:38.291 java[67280:894725] warning: <NSRemoteView: 0x7fa7e01006f0 com.apple.appkit.xpc.openAndSavePanelService ((null)) NSServiceViewControllerForTouchBarItem> determined it was necessary to configure <_NSFunctionRowPanel: 0x7fa7dc8e3c50> to support remote view vibrancy

**Comment by prasser** [comment] 2020-03-03 17:24
Thanks @gamblenull1996 for reporting this. This is, however, not related to the issue discussed here.

**Comment by prasser** [comment] 2020-05-25 21:52
@gamblenull1996 I can now confirm that the ARX GUI (neither the Installer, nor the App itself) runs in MacOS Catalina. We will need to update a few dependencies. I will create a new issue for this problem and close this issue now.

**Closed by prasser** 2020-05-25 21:52 UTC
