### ISSUE TITLE
Specifying Data Types for CSV Files Crashes ARX

### ISSUE THREAD

**Issue by chawco** [arx-deidentifier/arx#219] opened 2018-09-18 20:22 UTC
When specifying type information for a given column in a CSV ARX will automatically apply data cleansing to ensure types match throughout the column. It does this inside the CSV parser itself, via the iterators next() method. Unfortunately this is also the method used to extract headers from the CSV elsewhere in the code, which causes the data cleansing to be applied nulling out the headers, which then causes a NullPointerException deeper in ARX. Since the code appears to always assume headers are present, we should skip cleansing on the first row.

**Comment by prasser** [comment] 2018-09-20 16:06
Dear Chawco,

thanks for your interest in ARX! We are not able to reproduce this issue. Can you please provide a minimal example or a stacktrace?

Thanks
Fabian

**Comment by chawco** [comment] 2018-09-20 17:30
Hi Fabian,

It'll take a bit to work up an example -- I haven't reproduced it on master yet, but on 3.6.0 it's something like this (when using the library interface, not the GUI):

- We call `Data.create()` passing a CSV file with type information
- We then invoke `Anonymizer.anonymize()` passing in this `Data` object.
- Something internal calls `Data.getHandle()`
- This calls https://github.com/arx-deidentifier/arx/blob/61e7be6fcad0be7ba4d76f3704e488aa96b41353/src/main/org/deidentifier/arx/DataHandleInput.java#L72 

Which reads the header from the CSV file, whereupon the the `cleansing` flag means these columns get replaced with the string `"NULL"`. This is when the corruption occurs, but won't be directly reflected on the stack, since some other call then tries to use these parsed columns, and fails crashing with an NPE (due to not having a column named `"NULL"`).

It looks like this call path still exists in master, so it should be reproducible. Let me see if I can make an example in the next couple days.

It seems like the GUI uses the ImportAdapter API, which seems to skirt this issue, so it's likely not reproducible from there.

**Comment by prasser** [comment] 2018-09-20 18:27
Hi Craig,

thanks for the quick feedback! I already suspected that different code paths maybe involved here. With this information, it should be easier for us to replicate the bug if it is still present. Please note that there have been some changes to data loading since version 3.6.0 (we are currently at 3.7.1).

I'm a bit reluctant to simply accept your PR, because I'm afraid that it may have unintended side-effects on other code paths (e.g. those taken when using ImportAdapter). We will investigate further and see if we can find something. If you can provide an example, this would of course also be helpful.

Thanks for reporting this!
Fabian

PS: An obvious work-around would be to use ImportAdapter. Apart from that, the bug needs to be fixed of course, if it is still present.

**Comment by prasser** [comment] 2019-04-28 15:58
I finally found to the time to take a look into this and indeed the fix was a little more complex than suggested in your PR. There is a codepath where the first row may not be the header of the file. Fix has been committed to master. Thanks for your patience!

**Closed by prasser** 2019-04-28 15:58 UTC
