### ISSUE TITLE
Dialog for changing privacy parameters is difficult to use

### ISSUE THREAD

**Issue by mattharrison** [arx-deidentifier/arx#53] opened 2015-11-04 23:56 UTC
I would like to set the value to 5, but it only allows 2, then 7. I've unzipped the deid file and tried to change the setting in input/config.xml and output/config.xml, but it appears to have no effect.

Ideas?

**Comment by prasser** [comment] 2015-11-05 17:44
Thank you for your feedback!

I guess you are referring to the dialog for configuring privacy models? Which version of ARX are you using? And which OS? 

If you are using the current version (3.3.0), which I would recommend, you can double-click the control knob to bring up a dialog into which you should be able to enter any value. 

If you are using an older version, you may try to select the slider and use the left and right keys of your keyboard to change the value.

Even if any of my above suggestions helps to resolve the issue, I would be interested in knowing the details, because this is, of course, not the intended behaviour of the dialog.

**Comment by mattharrison** [comment] 2015-11-05 17:52
Thanks for the response. Am 3.3.0 on Mac. Double clicking works (didn't catch that in the docs).
 
As a slight aside, The dialog is 1000x better UX than the control knob. You should make the control knob come up when you double click :)

**Comment by prasser** [comment] 2015-11-05 17:57
:)

(1) It's not in the docs, yet. We currently have a rough time keeping the docs in sync with new developments
(2) You are absolutely right regarding the input dialog vs. control knob situation. We hope to soon find some time to further improve the dialogs.

As a reminder, I will leave this issue open for now

**Comment by prasser** [comment] 2015-12-09 10:15
Will be fixed in the upcoming release ARX 3.3.1

**Closed by prasser** 2015-12-09 10:15 UTC
Labels: enhancement, question
