### ISSUE TITLE
EU General Data Protection Regulation compliance support?

### ISSUE THREAD

**Issue by thejoecarroll** [arx-deidentifier/arx#126] opened 2017-08-18 05:05 UTC
Totally new to this tool, so please excuse the fact that my question/request is not informed by any practical knowledge of the software, but would it be possible to provide guidance on the website and in documentation, and possibly within the app itself regarding the suitability of different options for meeting the new GDPR regulations?

**Comment by prasser** [comment] 2017-08-18 09:00
Dear Joe,

thanks for your interest in ARX!

In theory, all methods implemented by the tool are relevant for implementing privacy protection as required by the GDPR.

In practice, the suitability of different methods (or combination of methods) heavily depends on context (i.e. use cases, types of data involved).

Consequently, it is basically impossible to give general advice. Instead, methods need to be selected and implemented by experts in accordance with guidelines (see e.g. the ENISA "Privacy and Data Protection by Design" guideline). Its likely that multiple tools and methods are needed.

I will close this issue now. Should you have further questions in this regard, please feel free to contact us at arx.deidentifier@gmail.com

Best regards
Fabian

**Closed by prasser** 2017-08-18 09:00 UTC
Labels: question
