### ISSUE TITLE
Add more default formats for dates (e.g. a format matching Oracle's date format)

### ISSUE THREAD

**Issue by nesokreso** [arx-deidentifier/arx#333] opened 2020-10-01 21:16 UTC
**Describe the bug**
Date parsing from oracle db doesn't work property in ARX Anonymization Tool

**To Reproduce**
1. Import the project attached [DEV_IVZ.PERSONS.IMPROVED.deid.zip](https://github.com/arx-deidentifier/arx/files/5314724/DEV_IVZ.PERSONS.IMPROVED.deid.zip)
2. Go to the Input data tab
3. Select a data field as DATE_OF_BIRTH or CREATION_DATE
4. With the existing formats i get always an error message 'Format does not match all data values' 
![image](https://user-images.githubusercontent.com/22678837/94863586-f5992200-043a-11eb-91f2-f2d4588d05ed.png)
5. The format of the input data looks as follows:
![image](https://user-images.githubusercontent.com/22678837/94863714-2da06500-043b-11eb-87e1-482bb8b7ea0a.png)
6. In my opinion the missing format 'yyyy-MM-dd hh:mm:ss.SSS' should be added on listDateFormats() in https://github.com/arx-deidentifier/arx/blob/master/src/main/org/deidentifier/arx/DataType.java but i'm not sure. Maybe there's in the usage from my side.

**Expected behavior**

**ARX GUI**
 - OS: Windows
 - Version 3.8.0

**Comment by arx-deidentifier** [comment] 2020-10-02 08:51
Hi Nenad, this seems to be more of a featu

**Comment by prasser** [comment] 2020-10-04 09:40
I'm not sure whether this really is a bug. Steps (1)-(3) mentioned above are incomplete and not sufficient to reproduce the (potential) problem. Are you trying to specify the data type "Date/Time" for the fields mentioned in Step (3) by selecting "Attribute metadata"->right click->"Date/Time"? If so, please note that the dialog also allows you to enter a format string manually. When entering "yyyy-MM-dd hh:mm:ss.SSS", everything should work as expected.

Am I missing something?

**Comment by nesokreso** [comment] 2020-10-05 15:27
Ok. I haven't realized that i can put in a custom format. With my custom format it would be recognized as a date and i can work with it. Maybe you could add this as an enhancement so i will let it open. I can't remove the bug label.

**Comment by prasser** [comment] 2022-06-11 16:31
If you can suggest concrete formats to add, we will be happy to do so (or you can provide a pull request). If so, please re-open the issue. I will close it now.

**Closed by prasser** 2022-06-11 16:31 UTC
Labels: enhancement, wontfix
