### ISSUE TITLE
SQL Server schema extract issue

### ISSUE THREAD

**Issue by DartecSystems** [arx-deidentifier/arx#82] opened 2016-11-07 12:50 UTC
Arx can't seem to handle tables in SQL Server that are not in the dbo schema.

**Comment by prasser** [comment] 2016-11-07 12:54
Thanks for reporting this issue. Do you mean that the import wizard only shows tables from the dbo schema?

**Comment by DartecSystems** [comment] 2016-11-07 13:09
Not quite. I guess the first sign there may be an issue comes in the early stages of the import wizard, where, although it shows all tables the connecting user account has access to, the objects not in the dbo schema show three question marks (rather than an indication of row count)

![image](https://cloud.githubusercontent.com/assets/15978275/20058633/dbab73e8-a4e9-11e6-9c06-e456de4435af.png)

Note, I moved the employee table into the dbo schema from its original schema to check the schema was the issue. Once I'd moved it to the dbo schema the three question marks are replaced by a valid value in the rows column. 

The next sign of trouble comes when you select a table. On the next wizard screen you get a message saying its can't read the metadata

![image](https://cloud.githubusercontent.com/assets/15978275/20058727/580e44a6-a4ea-11e6-9657-74fece52a954.png)

Then finally when you get to the end of the wizard and hit finish (to import the data), I get the below error.

![image](https://cloud.githubusercontent.com/assets/15978275/20058765/7e4d4018-a4ea-11e6-8ab7-ecde66444034.png)
 
For info, the extract is from a SQL Server 2014 instance.

**Comment by prasser** [comment] 2016-11-07 20:00
I see. Thanks for providing the details!

Unfortunately I do not have a SQL Server installation at hand. Can you run ARX from source (GitHub master) to help me fix this?

**Comment by prasser** [comment] 2016-11-07 20:53
The problem is related to the use of schemas. We have just committed a change to master which should fix the issue. We have tested the change with a PostgreSQL database with multiple schemas. Can you verify that it now works?

**Comment by prasser** [comment] 2016-11-25 13:44
As I haven't received any reply, yet, I will close this issue for now. If the problem remains, please file a new issue. Thanks, Fabian

**Closed by prasser** 2016-11-25 13:44 UTC
