### ISSUE TITLE
[Bugish] Nodes in hierarchy wizard do not always cover the displayed value range

### ISSUE THREAD

**Issue by srcds** [arx-deidentifier/arx#306] opened 2020-03-18 13:05 UTC
When using the hierarchy wizard for ratio or ordinal values the default nodes created on higher levels do not always contain all values of the (visually) underlying nodes.

**Example**
Level1:
100-300
300-500
500-1000
1000-2000

Level2: (displayed in GUI)
100-500 (manually created)
500-2000 (displayed as default)

Level2: (in final hierarchy)
100-500
500-900
900-1300
1300-1900
1900-2000

**Comment by prasser** [comment] 2022-06-11 16:28
Hard to understand. Can you provide an example?

**Comment by prasser** [comment] 2022-06-11 20:40
I think now I get it. This is very likely a duplicate of #353 which has been fixed today. Closing again.

**Closed by prasser** 2022-06-11 20:40 UTC
Labels: enhancement
