### ISSUE TITLE
Hierarchy has some missing values or duplicates

### ISSUE THREAD

**Issue by codingbutstillalive** [arx-deidentifier/arx#143] opened 2017-11-24 19:42 UTC
Hello there,

my dataset contains columns that also include multi-valued attributes like in this example column:

"EC_Aaa123"
"EC_Xxx, EC_Yyyy, EC_Z" 
"EC_Bbbb567"

(* You can think of proteins that can be labeled with one or multiple EC numbers that come from a hierarchical tree-like taxonomy. I am actually using some different taxonomies, but the principle is the same)

I know that ARX cannot generalize such multi-value strings, so I did it already in a preprocessing step. That is, I used preprocessing to simplify all multi-valued strings as much as possible with respect to the underlying taxonomy, using a most recent common ancestor approach.

Now I want to provide ARX this column along with a mock-up taxonomy, like so:

 EC_Aaa123;     EC_Aaa;     EC_A;     ****
 EC_Bbb567;    EC_Bbb;     EC_B;     ****
 EC_Xxx,EC_Yyyy,EC_Z;    ****;    ****;    ****

So, the idea is to give ARX the freedom to generalize at least the single-value attributes as best as possible, or to suppress the multi-valued ones. By the way, the items in multi-valued strings appear in sorted order, to avoid ambiguity.

This approach works except for some columns. ARX complains about missing values, but I don't know why. I checked the taxonomies several times.

Are there any latent restrictions that apply? For example, on the length of the strings in the input columns?

I really hope you can help me, as I already invested two weeks into the intricate preprocessing steps of the dataset. Unfortunately, I am not allowed to share that data.

**Comment by prasser** [comment] 2017-11-24 21:07
Hey there,

thanks for your interest in ARX! Can you please post the exact error message?

Thanks
Fabian

**Comment by codingbutstillalive** [comment] 2017-11-24 22:11
Hi Fabian!

Thanks a lot for your instant reply!

The error message comes from the class **GeneralizationHierarchy.java** and it says "Attribute 'name': hierarchy misses some values or contains duplicates". I could see it in the source file.

However, the codes also refers to _dictionary.getNumUniqueUnfinalizedValues(dimension)_ and I am not sure what restrictions apply there.

Best!

**Comment by prasser** [comment] 2017-11-24 22:24
At your service! ;)

You mentioned that you put quite some effort into making sure that there are no values in the dataset that are not covered by the hierarchy (missing values). So the follow-up question is obvious: have you also checked that your hierarchy does not contain any duplicate/ambiguous rules for generalizing  values? Hierarchies may not, on any level, contain rules with which the same value can be generalized into two or more different values - in other words: they have to be a tree. For example:

A;B;C
A;B;D

is not permitted.

Thanks,
Fabian

P.S.: Regardless of whether or not this turns out to be a bug you should file an issue asking us to make the error message more verbose. It would definitely help, if ARX would tell you the value for which the problem has been encountered.

**Comment by codingbutstillalive** [comment] 2017-11-25 08:39
Correct me again, if I am wrong. But I would say that the source code that issues the exception only checks the first level of the hierarchy, based on the 0-index being used there.

I totally agree that the error message needs to be more verbose. It would have helped me a lot.

How difficult would it be for me to run the whole thing in a debugging mode inside Eclipse or NetBeans? Or just to recompile the Jar with a more verbose error message?

Best

**Comment by codingbutstillalive** [comment] 2017-11-25 10:12
I really have to apologize for the inconvenience and efforts created. It turns out that the check of uniqueness was not working as expected. So, some items were in fact duplicates, cause two files were merged and the check was on data.frames instead of columns. I am sorry. Well, let's see now if this solves the issue.

Best

**Comment by prasser** [comment] 2017-11-25 10:21
Great to hear that you found the cause. I'll answer your questions anyway:

(3) It is possible to export output data, not import data. A workaround would be to apply an "anonymization" process that does not modify input data and to then export the output data produced.

(4) Defining a scientific sample will not have an effect on any of the checks. Your hierarchies still have to cover all items contained in the overall input dataset.

Should you have any further issues (it looks like as if you are working on a dataset which might be difficult to anonymize), please feel free to contact us: arx.deidentifier@gmail.com

Best,
Fabian

P.S.: Please create an issue requesting a more verbose error message.

**Comment by codingbutstillalive** [comment] 2017-11-25 10:36
Unfortunately, though this seemed to be the explanation, the issue still persists. So answers to my previous three questions could still help me to figure out what's causing the problem. Thanks.

**Comment by prasser** [comment] 2017-11-25 11:09
Ok, I see. I have create a branch arx/verbose that should produce a more detailed error message. Please give it a try.

I recommend you to use Eclipse. First pull the branch. In Eclipse, create a new Java project and point it at the directory that contains your local copy. Eclipse's wizard should automatically detect the correct project layout and setup - very straight-forward. Launch org.deidentifier.arx.gui.Main to run ARX. Then take a look at the exact error message.

P.S.: The code in the new verbose-branch is completely untested, so it may not work... If so, please let me know.

**Comment by codingbutstillalive** [comment] 2017-11-25 14:45
Dear Fabian!

Thanks so much for all of your efforts. I will give it a try, and give you feedback!

Best

**Comment by codingbutstillalive** [comment] 2017-11-25 15:42
I have a little problem when running it in Eclipse:

```
> Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
> 	Multi-catch parameters are not allowed for source level below 1.7
> 
> 	at org.deidentifier.arx.gui.Main.main(Main.java:63)
> 	at org.deidentifier.arx.gui.Main.main(Main.java:144)
```

I followed these steps so far:

> 1.) git clone https://github.com/arx-deidentifier/arx.git in $HOME/arx_download
> 2.) I copied and renamed "$HOME/arx_download/arx" into "$HOME/arx-3.6.0_debug"
> 3.) Opened Eclipse 
> 4.) New Project, "Java Project" (location set to "$HOME/arx-3.6.0_debug")
> 6.) Properties -> "Run/Debug Settings" -> New Configuration -> Main: org.deidentifier.arx.gui.Main
> 7.) Run

This resulted in this error.

**Comment by prasser** [comment] 2017-11-25 17:50
This error message is quite informative, though. You need to use a newer compiler or an appropriate compiler level. See, for example: https://stackoverflow.com/questions/18463067/eclipse-updating-the-compiler-compliance-to-1-7

**Comment by codingbutstillalive** [comment] 2017-11-27 09:00
Alright. I fixed it by selecting "Use project-specific compiler settings." and setting the compiler level to "1.7" there.

However, there is yet another problem.

```
java.lang.UnsatisfiedLinkError: Could not load SWT library, Reasons:
no swt-cocoa-4234 in java.library.path
no swt-cocoa in java.library.path
Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-cocoa-4234.so
```
I went to 

I have to admit that I haven't used Java and Eclipse for a really long time.

I went to _Project -> Properties -> Java Build Path -> Libraries_ and found some swt jars there, for example:

`swt-4.2.1-gtk-linux-x86_64.jar - ARX Testing/lib/swt`

I don't know why Eclipse is trying to locate it in _$HOME/.swt/_ then.

**Comment by prasser** [comment] 2017-11-27 09:03
Try the following: in the build path settings, make sure that *only* the correct swt.jar for your platform is included.

**Comment by codingbutstillalive** [comment] 2017-11-27 09:34
Okay. I will try that.

By the way. I found the solution to the problem with the error message from **GeneralizationHierarchy.java**. It's an intricate one, that I had suspected and tested before - but then forgotten as there were other problems masking its effect.

There are empty strings in the attribute colums, like so:

```
EC_Aaa123; EC_Aaa; EC_A; ****
EC_Bbb567; EC_Bbb; EC_B; ****

EC_Xxx,EC_Yyyy,EC_Z; ****; ****; ****
```

I really expected ARX to handle those, but it tries to look up the empty string in the hierarchy. I could fix this by running "find & replace" for substituting empty strings by "NAN". I then included NAN as an extra element into the hierarchy. Now the anonymization process runs through.

```
EC_Aaa123; EC_Aaa; EC_A; ****
EC_Bbb567; EC_Bbb; EC_B; ****

EC_Xxx,EC_Yyyy,EC_Z; ****; ****; ****
NAN; ****; ****; ****
```
However, the result is a non-anonymous dataset and I still have to make some tests, if ARX handles my generalization hierarchies as I expect it to.

One more question concerning that. Is the definition of the hierarchy as shown here valid?

P.S.: I will still have to investigate the problem with the "swt library". Thanks for the tipp!

**Comment by codingbutstillalive** [comment] 2017-11-27 09:42
FYI: I updated my last comment and made some corrections.

**Comment by prasser** [comment] 2017-11-27 09:46
OK. Now I have a few questions:

(1) What do you mean by "I found the solution to the problem with the error message [...]"? Did you try the "verbose" branch?
(2) Any hierarchy that does not raise an error when used with ARX is valid.
(3) What do you mean by "the result is a non-anonymous dataset"? Unless you made some very specific changes to ARX's settings this should never happen...

Thanks
Fabian

**Comment by codingbutstillalive** [comment] 2017-11-27 10:16
I am sorry for the confusion.

(1) I am referring to the original problem description in this thread. The error message "Attribute 'name': hierarchy misses some values or contains duplicates". This message was caused by the existence of empty strings in the attribute column.

(2) That's good to know. Thanks!

(3) I mean that the dataset was marked as "not being anonymous", i.e. an anonymization was not possible. The are no yellow or green nodes in the lattice. I didn't mean that ARX was doing something wrong when anonymizing.

**Comment by prasser** [comment] 2017-11-27 10:19
Regarding (3): Ah, I see. ARX does produce an anonymous output dataset, also in these cases, however. It's likely that all information has been removed. You should try to use a 100% suppression limit and ARX's local recoding feature.

**Comment by prasser** [comment] 2017-11-27 10:20
BTW: I will close this tread now. Please direct further questions towards: arx.deidentifier@gmail.com
And please try the verbose-branch. Thanks, Fabian

**Closed by prasser** 2017-11-27 10:20 UTC
