### ISSUE TITLE
Bug when constructing interval-based hierarchy

### ISSUE THREAD

**Issue by iylee7193** [arx-deidentifier/arx#353] opened 2021-04-08 06:44 UTC
Hello,

I have a question for Hierarchy feature.
I understand hierarchy, but I don't undertstand one.
For Hierarchy wizard, outputs of level-2 at 'Create a hierarchy by defining intervals' are diffrent from outputs of level-2 at 'Review the hierarchy'
If you see below picture, you can understand that.
![output of hierarchy](https://user-images.githubusercontent.com/82138691/113980188-21c9ab80-9881-11eb-8135-8c95b9aa8102.png)

I think two outputs of level-2 is same.
I can't understand that. If my opinion is wrong, could you describe that?

**Comment by prasser** [comment] 2021-04-08 16:21
Thanks for reporting this. Can you provide a minimal working example (e.g. a project file, or a dataset together with a step by step description) that we can use to reproduce the issue?

**Comment by iylee7193** [comment] 2021-04-09 00:12
Hello,
I attached zip file (project file, and hierarchy policy file)
[HierarchyIssue.zip](https://github.com/arx-deidentifier/arx/files/6282339/HierarchyIssue.zip)

I applied the hierarchy policy to 'age' column in project file, and I found the issue.

If you want more, could you please tell me that?

**Comment by prasser** [comment] 2021-04-09 20:08
Thanks again for reporting this! Your example is sufficient to reproduce the issue. This is a bug and we will fix it in the future. For now, let me suggest a quick fix to prevent the bug. It will work correctly, if you explicitly define each and every node also on the next level. Example:

![image](https://user-images.githubusercontent.com/4058833/114235102-f8dc1000-997f-11eb-9a0f-deff57a3e6e8.png)

Please also note that the hierarchy in your example doesn't make a lot of sense, because the groups on level 2 are defined identically to the groups on level 1. They should consist of merges of groups from the prior level, however. See the screenshot for one possible option.

**Comment by prasser** [comment] 2022-06-11 18:44
Has been fixed in current master by commit 308c1d9. Would you be able to test this again?

**Comment by prasser** [comment] 2022-06-13 08:47
Bugfix introduces new bugs. Reopening.

**Comment by prasser** [comment] 2022-06-13 09:45
Next try in commit 18cbf45. This passes all tests, so I'm confident that it fixes the bug without introducing new ones. Closing again.

**Closed by prasser** 2022-06-13 09:45 UTC
Labels: bug
